env:
  - CODECOV_TOKEN='aaa'
language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install -r requirements.txt
install:
  - python setup.py install
# command to run tests
script:
  - python -m coverage run
after_success:
  - codecov
